### ISSUE TITLE
Issue - Enum 상수 변경

### ISSUE THREAD

**Issue by kyoung-jnn** [YAPP-admin/yapp-web#17]
> https://engineering.linecorp.com/ko/blog/typescript-enum-tree-shaking/

**Enum type**이 **tree shaking**이 안되는 문제가 존재하네요.
사용되고 있는 **Enum type**을 변경해야 할 듯 합니다. 😢

**Comment by ksmfou98** [comment]
오호 .. ! 좋은 정보 감사합니다! const로 변경해야겠네욤 ㅋㅋ
