### ISSUE TITLE
21기 지원 관련 문구 업데이트

### ISSUE THREAD

**Issue by useonglee** [YAPP-admin/yapp-web#83]
1. 메인 이미지 관련
- 폰트 변경

3. 자주 묻는 질문
- 정기세션 관련 답변 수정
- 동아리 활동 관련 답변 수정

4. 홈 탭 컨텐츠 관련
- 운영 기수 21기로 변경

5. og 이미지 변경

**Comment by xodms0309** [comment]
모집 일정 및 자주 묻는 질문에서 정기 세션 일자 내용도 수정해야할 거 같아요!!!
